url: https://scidataucm.github.io
baseurl: ""

# Site settings
title: SciDataUCM
email: scidataucm@gmail.com
description: "Computer Science university students organization with a passion for data science"


# Team names, titles and social links
people:
- name: Alberto Pastor
  pic: 1
  position: Co-Founder
  social:
    - title: twitter
      url: https://twitter.com/albertopastormr
    - title: github
      url: https://github.com/albertopastormr
    - title: linkedin
      url: https://www.linkedin.com/in/albertopastormr/
    - title: email
      url: mailto:albertopastormr@gmail.com
    - title: instagram
      url: https://www.instagram.com/pastoreo11/

- name: Ivan Fermena
  pic: 2
  position: Co-Founder
  social:
    - title: twitter
      url: https://twitter.com/ivanf3rmena
    - title: github
      url: https://github.com/ivanfermena
    - title: linkedin
      url: https://www.linkedin.com/in/ivanfermena/

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: https://twitter.com/
    - title: github
      url: https://github.com/
    - title: linkedin
      url: https://www.linkedin.com/in/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/scidataucm
  - title: facebook
    url: 
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/SciDataUCM

# Postal address (add as many lines as necessary)
address:
  - line: Calle del Profesor José García Santesmases 9
  - line: 28040 Madrid

# Build settings
markdown: kramdown
permalink: pretty