url: "https://scidataucm.github.io"
baseurl: ""

# Site settingsUpdate 
title: SciDataUCMUpdate co
email: scidata@ucm.es
description: "Computer Science university students organization with a passion for data science"


# Team names, titles and social links
people:
- name: Alberto Pastor Moreno
  pic: 1
  position: Co-Founder
  social:
    - title: globe
      url: https://albertopastormr.me
    - title: envelope
      url: mailto:albertopastormr@gmail.com
    #- title: twitter url: https://twitter.com/albertopastormr
    - title: github
      url: https://github.com/albertopastormr
    - title: linkedin
      url: https://www.linkedin.com/in/albertopastormr/
    #- title: instagram url: https://www.instagram.com/albertopastormr/

- name: Ivan Fermena
  pic: 2
  position: Co-Founder
  social:
    - title: twitter
      url: https://twitter.com/ivanf3rmena
    - title: envelope
      url: mailto:ivanfermena@gmail.com
    - title: github
      url: https://github.com/ivanfermena
    - title: linkedin
      url: https://www.linkedin.com/in/ivanfermena/

- name: Manuel Monforte
  pic: 3
  position: Co-Founder
  social:
    - title: twitter
      url: https://twitter.com/manumonforte6
    - title: envelope
      url: mailto:abc@gmail.com
    - title: github
      url: https://github.com/manumonforte
    - title: linkedin
      url: https://www.linkedin.com/in/manuel-monforte-escobar-a58b69166/

- name: Gerardo Parra
  pic: 4
  position: Co-Founder
  social:
    - title: twitter
      url: https://twitter.com/gp_rossignoli
    - title: envelope
      url: mailto:abc@gmail.com
    - title: github
      url: https://github.com/gprossignoli
    - title: linkedin
      url: https://www.linkedin.com/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/scidataucm
  - title: instagram
    url: https://www.instagram.com/scidataucm/
  - title: envelope
    url: mailto:scidata@ucm.es
  - title: github
    url: https://github.com/SciDataUCM

# Postal address (add as many lines as necessary)
address:
  - line: Calle del Profesor José García Santesmases 9
  - line: 28040 Madrid

# Build settings
markdown: kramdown
permalink: pretty
